/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heightech;


import Databases.DatabaseConnection;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */

public class AddItem extends javax.swing.JFrame {

    String imagePth = null;
    
    /**
     * Creates new form AddItem
     */
    public static String adminName;
    public AddItem() {
        super("Iris Vision Dynamics ~Add A New Item");
        
        initComponents();
        
        setSize(1090, 600);
        
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelAdmin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelSupplier = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldSupplier = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDescription = new javax.swing.JLabel();
        jLabelPictureStatement = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelPicture = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();
        jLabelQuantity = new javax.swing.JLabel();
        jSpinnerQuantity = new javax.swing.JSpinner();
        jLabelPrice = new javax.swing.JLabel();
        jSpinnerprice = new javax.swing.JSpinner();
        jLabelModel = new javax.swing.JLabel();
        jTextFieldModel = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonEditItem = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add a new Item");

        jLabel1.setBackground(new java.awt.Color(240, 235, 83));
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel1.setOpaque(true);

        jLabelAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAdmin.setForeground(new java.awt.Color(230, 245, 141));
        jLabelAdmin.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(442, 442, 442))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 543, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 543, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 31, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 65);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelName.setText("Item Name: ");
        jPanel2.add(jLabelName);
        jLabelName.setBounds(40, 30, 102, 27);

        jLabelNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumber.setText("Item Number: ");
        jPanel2.add(jLabelNumber);
        jLabelNumber.setBounds(40, 150, 114, 22);

        jLabelClass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelClass.setText("Item Class:");
        jPanel2.add(jLabelClass);
        jLabelClass.setBounds(40, 210, 114, 22);

        jLabelSupplier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSupplier.setText("Item Supplier:");
        jPanel2.add(jLabelSupplier);
        jLabelSupplier.setBounds(40, 280, 114, 25);
        jPanel2.add(jTextFieldName);
        jTextFieldName.setBounds(190, 20, 213, 35);
        jPanel2.add(jTextFieldNumber);
        jTextFieldNumber.setBounds(190, 140, 213, 35);
        jPanel2.add(jTextFieldSupplier);
        jTextFieldSupplier.setBounds(190, 280, 213, 35);

        jComboBox1.setBackground(new java.awt.Color(249, 251, 244));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spare Part", "Complete Set", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(190, 210, 213, 38);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(534, 13, 33, 300);

        jLabelDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDescription.setText("Item Description:");
        jPanel2.add(jLabelDescription);
        jLabelDescription.setBounds(571, 208, 120, 25);

        jLabelPictureStatement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPictureStatement.setText("Item Image:");
        jPanel2.add(jLabelPictureStatement);
        jLabelPictureStatement.setBounds(571, 41, 99, 25);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(690, 220, 280, 80);

        jLabelPicture.setBackground(new java.awt.Color(153, 153, 255));
        jLabelPicture.setOpaque(true);
        jPanel2.add(jLabelPicture);
        jLabelPicture.setBounds(700, 50, 190, 140);

        jButtonBrowse.setBackground(new java.awt.Color(204, 255, 255));
        jButtonBrowse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBrowse.setText("Browse");
        jButtonBrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBrowseMouseClicked(evt);
            }
        });
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBrowse);
        jButtonBrowse.setBounds(910, 50, 90, 30);

        jLabelQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQuantity.setText("Quantity:");
        jPanel2.add(jLabelQuantity);
        jLabelQuantity.setBounds(40, 340, 114, 25);

        jSpinnerQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSpinnerQuantity.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanel2.add(jSpinnerQuantity);
        jSpinnerQuantity.setBounds(190, 340, 80, 30);

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrice.setText("Price (ksh):");
        jPanel2.add(jLabelPrice);
        jLabelPrice.setBounds(40, 400, 114, 25);

        jSpinnerprice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSpinnerprice.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanel2.add(jSpinnerprice);
        jSpinnerprice.setBounds(190, 400, 80, 30);

        jLabelModel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelModel.setText("Item Model: ");
        jPanel2.add(jLabelModel);
        jLabelModel.setBounds(40, 90, 102, 27);
        jPanel2.add(jTextFieldModel);
        jTextFieldModel.setBounds(190, 80, 213, 35);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 1090, 440);

        jButtonOk.setBackground(new java.awt.Color(105, 154, 240));
        jButtonOk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonOk.setText("Ok");
        jButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOkMouseClicked(evt);
            }
        });
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jButtonOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonOkKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonOk);
        jButtonOk.setBounds(440, 510, 110, 40);

        jButtonEditItem.setBackground(new java.awt.Color(105, 154, 240));
        jButtonEditItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditItem.setText("Edit");
        jButtonEditItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditItemMouseClicked(evt);
            }
        });
        jButtonEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditItemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditItem);
        jButtonEditItem.setBounds(610, 510, 110, 40);

        jButtonCancel.setBackground(new java.awt.Color(175, 23, 18));
        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(930, 510, 110, 40);

        jButtonDelete.setBackground(new java.awt.Color(105, 154, 240));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseClicked(evt);
            }
        });
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete);
        jButtonDelete.setBounds(770, 510, 110, 40);

        jButtonRefresh.setBackground(new java.awt.Color(91, 103, 240));
        jButtonRefresh.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh);
        jButtonRefresh.setBounds(270, 510, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonBrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBrowseMouseClicked
            MyPicFunc func = new MyPicFunc();
        imagePth = func.browseImg(jLabelPicture);        
    }//GEN-LAST:event_jButtonBrowseMouseClicked

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
       //refresh the table in the admin system
        refreshJTable();
        this.dispose();
       
    }//GEN-LAST:event_jButtonCancelMouseClicked
    
    
   // Check if the items exist
        public boolean isItemExist(String item)
    {
         boolean uExist = true;
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pss;
        ResultSet rss;
        
        try {
            pss = conn.prepareStatement("SELECT * FROM items WHERE Item_number = ?");
            
            pss.setString(1, jTextFieldNumber.getText());
            
            rss = pss.executeQuery();
            
            if(rss.next())
            {
                JOptionPane.showMessageDialog(null, "Item Already Exists!");
                return false;
            }
            else
            {
                return true;
            }
           
        } 
        catch (SQLException ex) {
            Logger.getLogger(ItemQuery.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        finally
        {
             try {
                 conn.close();
             } catch (SQLException ex) {
                 Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        
        return uExist;
    }

    public JLabel getjLabelNumber() {
        return jLabelNumber;
    }

    public void setjLabelNumber(JLabel jLabelNumber) {
        this.jLabelNumber = jLabelNumber;
    }

    public JTextField getjTextFieldModel() {
        return jTextFieldModel;
    }

    public void setjTextFieldModel(JTextField jTextFieldModel) {
        this.jTextFieldModel = jTextFieldModel;
    }
        
        
     public boolean verifyData()
    {
        // check for empty fields
        if(jTextFieldName.getText().equals("")  && jTextFieldNumber.getText().equals("") 
                || jTextFieldSupplier.getText().equals("") || jTextArea1.getText().equals("") || jTextFieldModel.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Fields Are Empty");
            return false;
        }
        
        else
        {
            return true;
        }
        
    }
    
     
     //Submit all the items of the table
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
       
    }//GEN-LAST:event_jButtonOkActionPerformed

    public JComboBox getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabelPicture() {
        return jLabelPicture;
    }

    public void setjLabelPicture(JLabel jLabelPicture) {
        this.jLabelPicture = jLabelPicture;
    }

    public JSpinner getjSpinner1() {
        return jSpinnerQuantity;
    }

    public void setjSpinner1(JSpinner jSpinner1) {
        this.jSpinnerQuantity = jSpinner1;
    }

    public JSpinner getjSpinnerprice() {
        return jSpinnerprice;
    }

    public void setjSpinnerprice(JSpinner jSpinnerprice) {
        this.jSpinnerprice = jSpinnerprice;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public void setjTextFieldName(JTextField jTextFieldName) {
        this.jTextFieldName = jTextFieldName;
    }

    public JTextField getjTextFieldNumber() {
        return jTextFieldNumber;
    }

    public void setjTextFieldNumber(JTextField jTextFieldNumber) {
        this.jTextFieldNumber = jTextFieldNumber;
    }

    public JTextField getjTextFieldSupplier() {
        return jTextFieldSupplier;
    }

    public void setjTextFieldSupplier(JTextField jTextFieldSupplier) {
        this.jTextFieldSupplier = jTextFieldSupplier;
    }

    private void jButtonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOkMouseClicked
             submitItem();
    }//GEN-LAST:event_jButtonOkMouseClicked

    private void jButtonEditItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditItemMouseClicked

    private void jButtonEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditItemActionPerformed
        // TODO add your handling code here:
         
           String itemName = jTextFieldName.getText();
            String itemNumber = jTextFieldNumber.getText();
            String itemClass = jComboBox1.getSelectedItem().toString();
            String itemDesc = jTextArea1.getText();

            try {
                jSpinnerprice.commitEdit();

                jSpinnerQuantity.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
            }
            int itemPrice = (Integer)jSpinnerprice.getValue();
            int itemQuantity = (Integer)jSpinnerQuantity.getValue();
            String itemModel = jTextFieldModel.getText();
            
            byte [] img = null;
            
            String itemSupplier = jTextFieldSupplier.getText();
            if(imagePth != null)
            {
                    try {
                   Path pth = Paths.get(imagePth);
                   img = Files.readAllBytes(pth);
                   
                   Items i = new Items(itemModel, itemName, itemNumber, itemClass, img, itemDesc, itemQuantity, itemPrice, adminName, itemSupplier);

                    ItemQuery Iq = new ItemQuery();
                    
                    //Refreshing the table
                    Iq.updateItem(i, true);
                  refreshJTable();
                  
               } catch (FileNotFoundException ex) {
                   Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
               } catch (IOException ex) {
                   Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
               }
            
            }
            
            else
            {
                Items i = new Items(itemModel, itemName, itemNumber, itemClass, null, itemDesc, itemQuantity, itemPrice, adminName, itemSupplier);

                 ItemQuery Iq = new ItemQuery();
                 Iq.updateItem(i, false);
                 
                 //refreshing the table
                  refreshJTable();
            }             
            jTextFieldName.setText("");
            jTextFieldNumber.setText("");
            jTextFieldSupplier.setText("");
            jTextArea1.setText("");
            jTextFieldModel.setText("");
            
        
        
    }//GEN-LAST:event_jButtonEditItemActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteMouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
      
            String itemNumber = jTextFieldNumber.getText();
            ItemQuery iq = new ItemQuery();
            
            int x = JOptionPane.showConfirmDialog(null, "Sure To Delete This Item?");
            
            if(x == 0)
            {
                 iq.deleteItems(itemNumber);
                 
                 //refresh the jtable
                 refreshJTable();
            }
            
            jTextFieldName.setText("");
            jTextFieldNumber.setText("");
            jTextFieldSupplier.setText("");
            jTextArea1.setText("");
            jTextFieldModel.setText("");
            
            
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        jTextFieldName.setText("");
            jTextFieldNumber.setText("");
            jTextFieldSupplier.setText("");
            jTextArea1.setText("");
            jTextFieldModel.setText("");
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonOkKeyPressed
       submitItem();
    }//GEN-LAST:event_jButtonOkKeyPressed

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    
    /** this function 
     * submits the items to database for storage
     */
    private void submitItem()
    {
         
        if(verifyData())
        {
            if(isItemExist(jTextFieldNumber.getText()))
            {
                 String itemName = jTextFieldName.getText();
            String itemNumber = jTextFieldNumber.getText();
            String itemClass = jComboBox1.getSelectedItem().toString();
            String itemDesc = jTextArea1.getText();

            //this is for getting the items that are entered by the keyboard
            try {
                jSpinnerprice.commitEdit();

                jSpinnerQuantity.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            int itemPrice = (Integer)jSpinnerprice.getValue();
            int itemQuantity = (Integer)jSpinnerQuantity.getValue();
            String itemModel = jTextFieldModel.getText();
            
            byte [] img = null;
            

            try {
                Path pth = Paths.get(imagePth);
                img = Files.readAllBytes(pth);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            String itemSupplier = jTextFieldSupplier.getText();

            
            Items i = new Items(itemModel, itemName, itemNumber, itemClass, img, itemDesc, itemQuantity, itemPrice, adminName, itemSupplier);

            ItemQuery Iq = new ItemQuery();
            Iq.insertItem(i);
            
            //Refresh the jtable
             refreshJTable();    
            
            jTextFieldName.setText("");
            jTextFieldNumber.setText("");
            jTextFieldSupplier.setText("");
            jTextArea1.setText("");
            jTextFieldModel.setText("");
                
                     
        }
        }
    }
    
    // This is the function for populating the jtable in the system
      public void refreshJTable()
    {
        
    
    }
        //setting upp the logo
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("MainLogo.png")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEditItem;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelPictureStatement;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelSupplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerQuantity;
    private javax.swing.JSpinner jSpinnerprice;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldSupplier;
    // End of variables declaration//GEN-END:variables
}
