/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Users;

import Databases.DatabaseConnection;
import heightech.ItemQuery;
import heightech.Items;
import heightech.MyDisplayModel;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author User
 */
public class ItemsAll extends javax.swing.JFrame {

    /**
     * Creates new form ItemsAll
     */
    public ItemsAll() {
        super("Iris Vision Dynamics");
        initComponents();
        populateJtable();
        jTableItems.setShowGrid(true);
        jTableItems.setGridColor(Color.black);
        
        JTableHeader th =jTableItems.getTableHeader();
        th.setBackground(Color.green);
        th.setFont(new Font("Tahoma",Font.BOLD, 12));
        th.setForeground(Color.blue);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableItems);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
      /** Display all the Items in the table */
    public final void populateJtable()
    {
        // getting the number of rows
        Connection conn = DatabaseConnection.getConnection();
        Statement statement;
        ResultSet rset;
        
        try {
            statement = conn.createStatement();
            
            rset = statement.executeQuery("SELECT COUNT(*) FROM users");
            
            
            
            // inserting the items to the table
        ItemQuery iq= new ItemQuery();
        ArrayList<Items> itList = iq.itemList();
        
        String[] colNames = {"", "Item Number","Item Name", "Price per Item", "Item Quantity"};
        Object [][] rows = new Object [itList.size()][9];
        int j = 1;
        float price = 0;
        while(rset.next())
        {
            for(int i = 0; i<itList.size(); i++)
            {
                rows[i][0] = j;
                rows[i][2] = itList.get(i).getItemName();
                rows[i][1] = itList.get(i).getItemNumber();
                rows[i][3] = itList.get(i).getItemPrice();
                rows[i][4] = itList.get(i).getItemQuantity();
                
                price+=itList.get(i).getItemPrice();
                
                MyDisplayModel model = new MyDisplayModel( rows, colNames);
                jTableItems.setModel(model);
                jTableItems.setRowHeight(30);
                
                // centering the elements in the table
                DefaultTableCellRenderer center = new DefaultTableCellRenderer();
                center.setHorizontalAlignment(JLabel.CENTER);
                jTableItems.setDefaultRenderer(String.class, center);
                jTableItems.setFillsViewportHeight(true);
                j++;
             }
        }
        
        } catch (SQLException ex) {
            Logger.getLogger(ItemQuery.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        finally
        {
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(ItemsAll.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    //setting upp the logo
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("MainLogo.png")));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemsAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableItems;
    // End of variables declaration//GEN-END:variables
}
